dependencies fix
Err.1:

```
Error: Cannot read config file: /Users/willin/.atom/packages/linter-eslint/node_modules/eslint-config-airbnb/base.js Error: ENOENT: no such file or directory, open '/Users/willin/.atom/packages/linter-eslint/node_modules/eslint-config-airbnb/base.js' Referenced from: /Users/willin/Documents/w2fs/auto-deployer/.eslintrc.json
Error: Cannot read config file: /Users/willin/.atom/packages/linter-eslint/node_modules/eslint-config-airbnb/base.js
Error: ENOENT: no such file or directory, open '/Users/willin/.atom/packages/linter-eslint/node_modules/eslint-config-airbnb/base.js'
Referenced from: /Users/willin/Documents/w2fs/auto-deployer/.eslintrc.json
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.Module._extensions..js (module.js:451:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```


Err.2:

```
Error: Cannot read config file: /Users/willin/.atom/packages/linter-eslint/node_modules/eslint-config-airbnb/base.js Error: ENOENT: no such file or directory, open '/Users/willin/.atom/packages/linter-eslint/node_modules/eslint-config-airbnb/base.js' Referenced from: /Users/willin/Documents/w2fs/auto-deployer/.eslintrc.json
Error: Cannot read config file: /Users/willin/.atom/packages/linter-eslint/node_modules/eslint-config-airbnb/base.js
Error: ENOENT: no such file or directory, open '/Users/willin/.atom/packages/linter-eslint/node_modules/eslint-config-airbnb/base.js'
Referenced from: /Users/willin/Documents/w2fs/auto-deployer/.eslintrc.json
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.Module._extensions..js (module.js:451:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```